version: '2.2'
services:
  web:
    build: .
    ports:
     - "31418:5000"
    cpus: 0.1
    mem_limit: 128M
    restart: on-failure
  redis:
    image: "redis:alpine"
    cpus: 0.1
    mem_limit: 128M
    restart: on-failure
